config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing_page'
  resources :inboxes
  get 'pricing', to: 'static_pages#pricing'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inbox.rb
class Inbox < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
  before_action :set_inbox, only: %i[ show edit update destroy ]

  # GET /inboxes or /inboxes.json
  def index
    @inboxes = Inbox.all
  end

  # GET /inboxes/1 or /inboxes/1.json
  def show
  end

  # GET /inboxes/new
  def new
    @inbox = Inbox.new
  end

  # GET /inboxes/1/edit
  def edit
  end

  # POST /inboxes or /inboxes.json
  def create
    @inbox = Inbox.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to inbox_url(@inbox), notice: "Inbox was successfully created." }
        format.json { render :show, status: :created, location: @inbox }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inboxes/1 or /inboxes/1.json
  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to inbox_url(@inbox), notice: "Inbox was successfully updated." }
        format.json { render :show, status: :ok, location: @inbox }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inboxes/1 or /inboxes/1.json
  def destroy
    @inbox.destroy

    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: "Inbox was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inbox
      @inbox = Inbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inbox_params
      params.require(:inbox).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def pricing
  end

  def privacy
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/inboxes/_form.html.erb
<%= form_with(model: inbox) do |form| %>
  <% if inbox.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inbox.errors.count, "error") %> prohibited this inbox from being saved:</h2>

      <ul>
        <% inbox.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/_inbox.html.erb
<div id="<%= dom_id inbox %>">
  <p>
    <strong>Name:</strong>
    <%= inbox.name %>
  </p>

</div>

app/views/inboxes/edit.html.erb
<h1>Editing inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Show this inbox", @inbox %> |
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inboxes</h1>

<div id="inboxes">
  <% @inboxes.each do |inbox| %>
    <%= render inbox %>
    <p>
      <%= link_to "Show this inbox", inbox %>
    </p>
  <% end %>
</div>

<%= link_to "New inbox", new_inbox_path %>

app/views/inboxes/new.html.erb
<h1>New inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inbox %>

<div>
  <%= link_to "Edit this inbox", edit_inbox_path(@inbox) %> |
  <%= link_to "Back to inboxes", inboxes_path %>

  <%= button_to "Destroy this inbox", @inbox, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<hr>
<center>
  <h5>
    <%= link_to_unless_current 'Pricing', pricing_path %>
    <%= link_to_unless_current 'Privacy', privacy_path %>
    <%= link_to_unless_current 'Terms', terms_path %>
  </h5>
</center>

app/views/shared/_navigation.html.erb
<center>
  <h1>
    <%= link_to_unless_current Rails.application.class.module_parent.name, root_path %>
  </h1>
<%= link_to_unless_current 'Inboxes', inboxes_path %>
<%= link_to_unless_current 'New Inbox', new_inbox_path %>
</center>
<hr>

app/views/static_pages/landing_page.html.erb
<h1>StaticPages#landing_page</h1>
<p>Find me in app/views/static_pages/landing_page.html.erb</p>

app/views/static_pages/pricing.html.erb
<h1>StaticPages#pricing</h1>
<p>Find me in app/views/static_pages/pricing.html.erb</p>

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/terms.html.erb
<h1>StaticPages#terms</h1>
<p>Find me in app/views/static_pages/terms.html.erb</p>